In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv('mail_data.csv')

In [ ]:
print(df)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [ ]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [ ]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.25)

In [ ]:
x_train.describe()

count                       4179
unique                      3923
top       Sorry, I'll call later
freq                          24
Name: Message, dtype: object

In [ ]:
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(x_train)
X_test_vectorized = vectorizer.transform(x_test)

In [ ]:
x_train_count.toarray()

NameError: name 'x_train_count' is not defined

In [ ]:
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)

MultinomialNB()

In [ ]:
predictions = classifier.predict(X_test_vectorized)

In [ ]:
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
report = classification_report(y_test, predictions)

In [ ]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{report}")

Accuracy: 0.9863603732950467
Confusion Matrix:
[[1216    5]
 [  14  158]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1221
           1       0.97      0.92      0.94       172

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [5]:
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/receive_emails', methods=['POST'])
def receive_emails():
    try:
        data = request.get_json()
        emails = data.get('emails', [])

        # Process the emails as needed
        print("Received emails:", emails)

        response = {
            'success': True,
            'message': 'Emails received successfully.'
        }
        return jsonify(response)

    except Exception as e:
        error_response = {
            'success': False,
            'message': f'Error: {str(e)}'
        }
        return jsonify(error_response)

# if __name__ == '__main__':
    from flask import Flask, request, jsonify





In [ ]:
email_spam = ["hello"]
email_spam_count = vectorizer.transform(email_spam)
classifier.predict(email_spam_count)

array([0])

In [ ]:
email_ham = ["reward money click"]
email_ham_count = vectorizer.transform(email_ham)
classifier.predict(email_ham_count)

array([1])

In [ ]:
ham_messages = [message for message, label in zip(df.Message, predictions) if label == 0]
spam_messages = [message for message, label in zip(df.Message, predictions) if label == 1]

In [ ]:
ham_messages

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'Ok lar... Joking wif u oni...',
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
 'U dun say so early hor... U c already then say...',
 "Nah I don't think he goes to usf, he lives around here though",
 "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
 'Even my brother is not like to speak with me. They treat me like aids patent.',
 'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
 "I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.",
 'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11